#!/usr/bin/env node
/**
 * テスト用の Codex CLI モック。
 * `codex exec --json` の JSONL イベント形式（allowlist 対象種別 + reasoning 除外分も
 * 意図的に混在）を再現し、環境変数で挙動を変える:
 * - MOCK_LOGGED_OUT:  login status を失敗させる
 * - MOCK_WRITE_FILE:  exec 時に cwd へファイルを書き出す（Git 差分検出のテスト用）
 * - MOCK_SLEEP_MS:    exec の所要時間（タイムアウト・ロックのテスト用）
 * - MOCK_SESSION_ID:  新規セッションに付与する ID
 * - MOCK_GIT_COMMIT:  exec 時に cwd で git commit する（HEAD 変化検出のテスト用）
 * - MOCK_HELP_MISSING_JSON: exec --help の応答から --json を欠落させる（未対応バージョン検知テスト用）
 */
import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";

const args = process.argv.slice(2);
const emit = (o) => console.log(JSON.stringify(o));

if (args[0] === "--version") {
  console.log("codex-cli 0.0.0-mock");
  process.exit(0);
}

if (args[0] === "exec" && args.includes("--help")) {
  const flags = process.env.MOCK_HELP_MISSING_JSON
    ? ["--sandbox <MODE>", "codex exec resume <SESSION_ID>"]
    : ["--json", "--sandbox <MODE>", "codex exec resume <SESSION_ID>"];
  console.log("USAGE: codex exec [OPTIONS] PROMPT\n" + flags.join("\n"));
  process.exit(0);
}

if (args[0] === "login" && args[1] === "status") {
  if (process.env.MOCK_LOGGED_OUT) {
    console.error("Not logged in");
    process.exit(1);
  }
  console.log("Logged in using ChatGPT");
  process.exit(0);
}

if (args[0] === "exec") {
  const resume = args[1] === "resume";
  const sessionId = resume ? args[2] : process.env.MOCK_SESSION_ID || "mock-session-1";
  const prompt = args[args.length - 1];

  const sleep = Number(process.env.MOCK_SLEEP_MS || 0);
  if (sleep > 0) await new Promise((r) => setTimeout(r, sleep));

  if (process.env.MOCK_WRITE_FILE) {
    fs.writeFileSync(
      path.resolve(process.cwd(), process.env.MOCK_WRITE_FILE),
      "generated by mock codex\n"
    );
  }

  emit({ type: "thread.started", thread_id: sessionId });
  // allowlist から除外されるべき reasoning イベント（無視されることを確認するため混入）
  emit({ type: "reasoning", text: "これは思考過程であり中継・保存されてはならない" });
  emit({
    type: "item.completed",
    item: { type: "command_execution", command: "npm test", exit_code: 0, status: "completed" },
  });
  const envCheck = process.env.MOCK_PRINT_ENV
    ? ` ENV_CHECK GIT_SSH_COMMAND=${process.env.GIT_SSH_COMMAND} GITHUB_TOKEN_SET=${process.env.GITHUB_TOKEN !== undefined} SSH_AUTH_SOCK_SET=${process.env.SSH_AUTH_SOCK !== undefined}`
    : "";
  emit({
    type: "item.completed",
    item: {
      type: "agent_message",
      text: `MOCK_REPLY(${resume ? "resume" : "new"}) cwd=${process.cwd()} prompt=${prompt}${envCheck}`,
    },
  });

  if (process.env.MOCK_GIT_COMMIT) {
    fs.writeFileSync(path.resolve(process.cwd(), "committed-by-codex.txt"), "x\n");
    execFileSync("git", ["add", "."], { cwd: process.cwd() });
    execFileSync("git", ["-c", "user.email=mock@example.com", "-c", "user.name=mock", "commit", "-q", "-m", "mock commit"], {
      cwd: process.cwd(),
    });
  }

  emit({ type: "turn.completed", usage: { input_tokens: 10, output_tokens: 5 } });
  process.exit(0);
}

console.error("mock-codex: unknown args: " + args.join(" "));
process.exit(2);
